increase declared MSRV to 1.42
up through rust-1.41.1, we get this error:

```
error[E0432]: unresolved import `proc_macro`
 --> /Users/warner/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-derive-0.3.1/src/lib.rs:1:5
  |
1 | use proc_macro::TokenStream;
  |     ^^^^^^^^^^ help: a similar path exists: `syn::proc_macro`
```

I think that means rustyline-derive removed the `extern crate proc_macro`
which was required until rust-1.42, or something similar, thus raising their
own effective MSRV.